version: 0.2

phases:
  install:
    runtime-version:
      java: openjdk8

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase
  

  build:
    commands:
      - echo Build started on 'date'
      - cd springboot
      - mvn install

  post_build:
    commands:
      - echo Build completed on 'date'

    
artifacts:
  files:
    - springboot/target/springboot-0.0.1-SNAPSHOT.jar


